-- Create items table
create table items (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  image_url text not null,
  seller_url text not null,
  bid numeric not null,
  current_bid numeric not null,
  market numeric not null,
  date timestamp with time zone not null,
  seller text not null,
  auctions integer default 0,
  archived boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table items enable row level security;

-- Create a policy that allows all operations for now
create policy "Enable all operations for all users" on items
  for all
  using (true)
  with check (true); 